CREATE DATABASE CONTEXTX
GO
USE CONTEXTX

CREATE TABLE TBL_ADMIN
(
AD_ID INT IDENTITY PRIMARY KEY,
AD_NAME NVARCHAR(20) NOT NULL UNIQUE,
AD_PASSWORD NVARCHAR(20) NOT NULL
)

CREATE TABLE TBL_QUESTIONS
(
QUESTION_ID INT IDENTITY PRIMARY KEY,
Q_TEXT NVARCHAR(MAX) NOT NULL,
OPA NVARCHAR(20) NOT NULL UNIQUE,
OPB NVARCHAR(20) NOT NULL UNIQUE,
OPC NVARCHAR(20) NOT NULL UNIQUE,
OPD NVARCHAR(20) NOT NULL UNIQUE,
COP NVARCHAR(20) NOT NULL,
Q_FK_CATID INT
)

CREATE TABLE TBL_KHACH
(
S_ID INT IDENTITY PRIMARY KEY,
S_NAME NVARCHAR(20) NOT NULL UNIQUE,
S_PASSWORD NVARCHAR(20) NOT NULL,
S_IMAGE NVARCHAR(MAX) NOT NULL
)

CREATE TABLE TBL_SETEXAM
(
EXAM_ID INT IDENTITY PRIMARY KEY,
EXAM_DATE DATETIME,
EXAM_FK_S INT,
EXAM_NAME NVARCHAR(50) NOT NULL,
EXAM_STD_SCORE INT
)

CREATE TABLE TBL_CATEGORY
(
	CAT_ID INT IDENTITY PRIMARY KEY,
	CAT_NAME NVARCHAR(50) NOT NULL,
	CAT_FK_ADID INT,
)
CREATE TABLE TBL_QUESTIONS
(
QUESTION_ID INT IDENTITY PRIMARY KEY,
Q_TEXT NVARCHAR(MAX) NOT NULL,
OPA NVARCHAR(20) NOT NULL UNIQUE,
OPB NVARCHAR(20) NOT NULL UNIQUE,
OPC NVARCHAR(20) NOT NULL UNIQUE,
OPD NVARCHAR(20) NOT NULL UNIQUE,
COP NVARCHAR(20) NOT NULL,
Q_FK_CATID INT
)
ALTER TABLE TBL_SETEXAM ADD CONSTRAINT FK_TBL_KHACH_TBL_SETEXAM FOREIGN KEY (EXAM_FK_S) REFERENCES TBL_KHACH(S_ID)
ALTER TABLE TBL_CATEGORY ADD CONSTRAINT FK_TBL_CATEGORY_TBL_ADMIN FOREIGN KEY (CAT_FK_ADID) REFERENCES TBL_ADMIN(AD_ID)
ALTER TABLE TBL_QUESTIONS ADD CONSTRAINT FK_TBL_QUESTIONS_TBL_CATEGORY FOREIGN KEY (Q_FK_CATID) REFERENCES TBL_CATEGORY(CAT_ID)

INSERT INTO TBL_ADMIN VALUES ('admin', 'admin')
INSERT INTO TBL_ADMIN VALUES ('admin2', 'admin')
