CREATE DATABASE DBQuiz
GO
USE DBQuiz

CREATE TABLE TBL_ADMIN
(
AD_ID INT IDENTITY PRIMARY KEY,
AD_NAME NVARCHAR(20) NOT NULL UNIQUE,
AD_PASSWORD NVARCHAR(20) NOT NULL
)

CREATE TABLE TBL_QUESTIONS
(
QUESTION_ID INT IDENTITY PRIMARY KEY,
Q_TEXT NVARCHAR(MAX) NOT NULL,
OPA NVARCHAR(20) NOT NULL UNIQUE,
OPB NVARCHAR(20) NOT NULL UNIQUE,
OPC NVARCHAR(20) NOT NULL UNIQUE,
OPD NVARCHAR(20) NOT NULL UNIQUE,
COP NVARCHAR(20) NOT NULL
)

CREATE TABLE TBL_KHACH
(
S_ID INT IDENTITY PRIMARY KEY,
S_NAME NVARCHAR(20) NOT NULL UNIQUE,
S_PASSWORD NVARCHAR(20) NOT NULL,
S_IMAGE NVARCHAR(MAX) NOT NULL
)

CREATE TABLE TBL_SETEXAM
(
EXAM_ID INT IDENTITY PRIMARY KEY,
EXAM_DATE DATETIME,
EXAM_FK_STU INT FOREIGN KEY REFERENCES TBL_STUDENT (S_ID),
EXAM_NAME NVARCHAR(50) NOT NULL,
EXAM_STD_SCORE INT
)

CREATE TABLE TBL_CATEGORY
(
	CAT_ID INT IDENTITY PRIMARY KEY,
	CAT_NAME NVARCHAR(50) NOT NULL,
	CAT_FK_ADID INT FOREIGN KEY REFERENCES TBL_ADMIN (AD_ID)
)

CAT_FK_ADID INT FOREIGN KEY REFERENCES TBL_ADMIN (AD_ID)

SELECT * FROM TBL_QUESTIONS

INSERT INTO TBL_ADMIN VALUES ('admin', 'admin')
INSERT INTO TBL_ADMIN VALUES ('admin2', 'admin')
